# Generated by Django 5.0.6 on 2024-06-01 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_student_date_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='duration_field',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
