# Generated by Django 5.0.6 on 2024-06-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_student_decimal_field_student_duration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_time_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='decimal_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='duration_field',
        ),
    ]
